### PR TITLE
Feature/split unit tests

### LINKED ISSUE #540: Break the testing class apart :: test/unit/SendGridTest.php
All our tests are in one class. Break them up by type and use a base test class.

Make sure all the tests still run and report the same way as before.

https://codeclimate.com/github/sendgrid/sendgrid-php/test/unit/SendGridTest.php#issue_59f668408905d74fee00001e

### PR DESCRIPTION
**Pull request by pxgamer**
# Fixes #540

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Splits up the test suite into multiple files as per #540

### Travis tests

- [General Information](https://travis-ci.org/pxgamer/sendgrid-php/builds/295089806)
- [PHP 5.6](https://travis-ci.org/pxgamer/sendgrid-php/jobs/295089807)
- [PHP 7.0](https://travis-ci.org/pxgamer/sendgrid-php/jobs/295089808)

### CODE REVIEW

**Comment by pxgamer** [comment]
Well, Travis failed. They seem to be having issues recently. :confused:

**Comment by mbernier** [comment]
I just kicked it over, we will see what Travis says here in a bit!

**Comment by pxgamer** [comment]
Well... that definitely didn't work. 😋 

I'll have a look a bit later when I get off work, and see if I can get it working again.

**Comment by pxgamer** [comment]
This seems to all be working, except for one test.

It looks like this test has never passed though.
https://github.com/sendgrid/sendgrid-php/commits/master/test/unit/FilesExistTest.php

**Comment by thinkingserious** [comment]
No worries @pxgamer, that test is expected to fail at the moment.

This PR has been added to our backlog for review, thanks!

**Comment by mbernier** [comment]
We are good to go, thank you @pxgamer!!

**Comment by thinkingserious** [comment]
Hello @pxgamer,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
