### PR TITLE
PHPDoc & code improvements

### LINKED ISSUE #619: Invalid inline documentation
Hi, nice work on the inline commenting although some mistakes have been made! Easily fixable and will probably send a pull-request to fix it soon.

The variables you comments with `//` but those also have to be done with `/**/` or PHPDoc won't accept them.

Shown below:

1c320eb43040ce81a01c0e2d7 1

### PR DESCRIPTION
**Pull request by martijnmelchers**
# Fixes # 
Fixes #619 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Improved PHPdoc warnings
- Improve code style & self assignments

### CODE REVIEW

**Comment by martijnmelchers** [comment]
There were some errors I couldn't fix.

# getPersonalizationCount()
File: Mail.php
dd2ed4c7a7f63970cd02dda4f 1
# getSubstitutions()
File: Mail.php
022e7e026ad5a4430f3deaaf9 1
# Self assignment
File: Mail.php
cd7615825b7d6caa6b6397daf 1

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,

Looks like those issues can be fixed by modifying the code. I'll take a deeper look when this bubbles up my backlog.

Thanks!

With Best Regards,

Elmer

**Comment by martijnmelchers** [comment]
This can be merged now too! @thinkingserious

**Comment by emirb** [comment]
@martijnmelchers you can define these two magic methods by adding a docblock on the top of the file with `@method` tags, then the IDE will also recognise them.

**Comment by thinkingserious** [comment]
@martijnmelchers,

What linter are you using locally and with what settings? 

I'm getting some clashes with my linter (phpcs) in visual studio code with the standard set to be PSR2. Namely:

* "The closing parenthesis and the opening brace of a multi-line function declaration must be on the same line"
* Some Line exceeds 120 characters

Thanks!

**Comment by martijnmelchers** [comment]
I just use IntelliJ lint, I don't know what specific lint settings I have, I could see if I can set it to PSR2 though.

**Comment by thinkingserious** [comment]
Hello @martijnmelchers!

It looks like you can change that setting [like this](https://confluence.jetbrains.com/display/PhpStorm/PHP+Code+Sniffer+in+PhpStorm). Check out this section: "1.2. Configure PHP Code Sniffer as a PhpStorm inspection"

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
