### PR TITLE
Send message with html as content type

### PR DESCRIPTION
**Pull request by manfordbenjamin**
Add an example for sending email in html format as content type.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=574) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=574) before we can accept your contribution.<br/><hr/>**Benjamin Manford** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=574) it.</sub>

**Comment by thinkingserious** [comment]
Thanks @manfordbenjamin!

Do you mind [signing our CLA](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=574) so we can merge your PR? It's a quick web form that should not take more than a few minutes.

Thanks!

With Best Regard,

Elmer

**Comment by manfordbenjamin** [comment]
Signed.

Regards,
Benjamin

**Comment by thinkingserious** [comment]
Hi @manfordbenjamin,

It looks like you don't have an email address associated with your GitHub account. In order to successfully sign our CLA, you need to have an email address attached to your GitHub account. Could you please add an email address to your GitHub account and then try signing the CLA again? 

Thank you!

**Comment by manfordbenjamin** [comment]
I have an email address associated to my github account. I tried signing again but i can't. There's a message saying i have already signed it.

**Comment by thinkingserious** [comment]
Looking at the [commit message](https://github.com/sendgrid/sendgrid-php/pull/574/commits), it looks like the commit was not made with your GitHub account.

Maybe the easiest course of action is to close this PR and re-commit your changes under your GitHub account.

**Comment by manfordbenjamin** [comment]
Alright

**Pull request closed without merging**
