### PR TITLE
Allow for Dynamic Templates Implementation

### LINKED ISSUE #648: Add Dynamic Template Support
#### Issue Summary

On 7/24/2018, our team publicly launched dynamic content for transactional templates. It is now available for all customers sending over v3 of our Mail Send API. Iterate over lists, handle conditionals and more, thanks to native support for a subset of Handlebars syntax!

More information can be found in our [blog post announcement](https://sendgrid.com/blog/how-to-use-sendgrids-dynamic-templates-for-your-transactional-emails/).

You can currently use this feature by manually creating the request body as [shown here](https://github.com/sendgrid/sendgrid-php/blob/master/USAGE.md#v3-mail-send). 

Now, we need to create helper code and examples for this SDK.

#### Acceptance Criteria

* [Implement a helper similar to what we have for the legacy templates](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates)
* Update the [USE_CASES.md](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#transactional-templates) example to demonstrate the new *Dynamic Templates* using the helper and re-name the current example to *Legacy*

#### Documentation
- [Reference Implementation](https://github.com/sendgrid/sendgrid-nodejs/pull/691#issuecomment-407490342)
- [How to Send an Email With Dynamic Transactional Templates](https://sendgrid.com/docs/User_Guide/Transactional_Templates/how_to_send_an_email_with_transactional_templates.html)
- [Using Handlebars](https://sendgrid.com/docs/User_Guide/Transactional_Templates/Using_handlebars.html)
- [Interactive API Docs](https://dynamic-templates.api-docs.io/3.0/mail-send-with-dynamic-transactional-templates/v3-mail-send)

### PR DESCRIPTION
**Pull request by mwillbanks**
# Fixes #648 

### Checklist
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guide] and my PR follows them.
- [X] I updated my branch with the master branch.
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [X] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds dynamic template support by adding a new helper object, new methods into the mail and personalization classes.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=657) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=657) before we can accept your contribution.<br/><hr/>**Mike Willbanks** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=657) it.</sub>

**Comment by thinkingserious** [comment]
Thank you @mwillbanks!

**Comment by thinkingserious** [comment]
cc @martijnmelchers

**Comment by jideokus** [comment]
Hi. Thanks for working on this. Any news on this?

**Comment by mwillbanks** [comment]
@jideokus I'm actually using my branch with these changes in production right now.  It works pretty much the exact same way as substitutions except that you can use anything as a parameter that is JSON Serializable.

```
$mail->addDynamicTemplateData('arrayData', ['one', 'two', 'three']);
$mail->addDynamicTemplateData('number', 1);
$mail->addDynamicTemplateData('boolean', true);
$mail->addDynamicTemplateData('string', 'foo');
```

**Comment by jideokus** [comment]
Excellent. Thanks @mwillbanks. I'll take it for a spin. I have a bunch of emails waiting to be fired with this 😁

**Comment by thinkingserious** [comment]
Hello @mwillbanks,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by thinkingserious** [comment]
Here is the [final diff](https://github.com/sendgrid/sendgrid-php/commit/b72ee445bf9e80636d6125c26c5134e62777d16b).

**Comment by luciano-jr** [comment]
Hi, first of all, thanks @mwillbanks for your contribution! 

I want to fetch all created templates from the API using as the example shows (https://github.com/sendgrid/sendgrid-php/blob/7ed980a6d27bb584969d4e8da82b70ae30951954/examples/templates/templates.php#L34). But I guess this PR does not cover that point, did it?

**Comment by thinkingserious** [comment]
@luciano-jr,

Please try the following:

```php
<?php
require 'vendor/autoload.php'; // If you're using Composer (recommended)
// Comment out the above line if not using Composer
// require("<PATH TO>/sendgrid-php.php");
// If not using Composer, uncomment the above line and
// download sendgrid-php.zip from the latest release here,
// replacing <PATH TO> with the path to the sendgrid-php.php file,
// which is included in the download:
// https://github.com/sendgrid/sendgrid-php/releases

$apiKey = getenv('SENDGRID_API_KEY');
$sg = new \SendGrid($apiKey);
$query_params = json_decode('{"generations": "dynamic,legacy"}');
$response = $sg->client->templates()->get(null, $query_params);
print $response->statusCode() . "\n";
print $response->body() . "\n";
print_r($response->headers());
```

With Best Regards,

Elmer

**Pull request merged**
