### PR TITLE
New version of Sengrid-PHP for Guzzle 6.x support

### PR DESCRIPTION
**Pull request by taz77**
I have been working on a fork of the SendGrid-PHP library to support Guzzle 6.x. This fork only supports PHP 5.5+ and eventually PHP 7.0 as testing with the RC's for PHP 7.0 has started. The decesion to do this was also for my support of the Drupal Sendgrid module. Drupal 8.0 includes Guzzle 6.x making integration really easy for the Drupal CMF for 8.x and beyond. It also supports Drupal 7.x by using the another contrib module that provides Composer.

I made a grave mistake by commiting to master branch in my fork. I should have created a branch! But what is done is done. I updated all the classes and methods and have run Travis CI using my own account and the existing PHPUnit test adapted to exclude PHP 5.3 and 5.4.

I would love for Sendgrid to consider this contribution as a new version of Sendgrid-PHP. This would allow you to continue support for PHP 5.3 by creating a new version of the Sendgrid library.

This pull request isn't meant to be the final version. I know there are other changes that need to be made. This pull request could essentially be looked at as a request to make a new branch in SendGrid-PHP library - a 4.x.x branch.

Lastly, along with the testing. I am using this on a production website via custom composer.json's: https://www.swingsurgeon.com

Thoughts?

### CODE REVIEW

**Comment by taz77** [comment]
Any word on this? I am needing this for the Drupal module I am about to publish so I want to get this into packagist. I rather not register a fork of this library, but if SendGrid has no interest in taking this as a contribution I will happily register this as a fork and just assume maintenance of it.

**Comment by thinkingserious** [comment]
First of all, thank you! We greatly appreciate the work you have done to move this library into the future.

Unfortunately, we can make these changes to our current officially supported library as there is still significant php 5.3 usage. 

That said, when the time comes we will likely draw from your work. For now, I suggest you maintain this fork on your own repo as a contribution to the php community who would prefer to use the latest Guzzle and php 5.5 or greater. 

I will be watching your fork in case there are any changes we can help with.

Also, I may add this support as part of the official library while maintaining backwards compatibility, but I'll need some time to determine if that's possible and how to proceed.

**Comment by taz77** [comment]
Thanks for the feedback. I plan on getting this into Packagist in some form under my namespace.

I will try and keep it update with the changes you guys make.

**Comment by thinkingserious** [comment]
Awesome! Thanks again!

**Comment by taz77** [comment]
FYI, I have this fork in Packagist now. I have some work to catch up on changes you guys have made.

https://packagist.org/packages/fastglass/sendgrid

Please let me know if you see any problems with anything in the package. I attempted to make it completly clear that this is a fork and not the official library.

**Comment by thinkingserious** [comment]
That is awesome @taz77!

Realistically, it will be some time before I can give it a proper review, but do please keep me in the loop.

**Comment by taz77** [comment]
No problem. I'm using it already in a few production websites. I been trying to go through your commits to see what I need to port over.

**Comment by achraf52** [comment]
@taz77 Is the fork on Packagist ready for production? I mean, no obvious bugs or leftover work to do.

I noticed the Travis build widget shows "build failing" on /taz77/sendgrid-php/ but clicking it seems to redirect to a picture and not a real Travis build page, are you aware of that?

@thinkingserious How is the plan to upgrade /sendgrid/sendgrid-php/ to Guzzle 6.x as for now, as PHP 7 is now released, I don't think it's reasonable to continue supporting PHP 5.3 users anymore.

Moreover, most development and production environments I've seen in the last year have PHP 5.5.x and updates to PHP 7 are surely coming in the next few months.Anyone really using PHP 5.3 and doesn't wish to upgrade their PHP version should just stick to the sendgrid-php v4.0.x library and deal with it.

**Comment by taz77** [comment]
@achraf52 The fork works great. I am running on a production eCommerce site. I developed the fork because of a new release of the Drupal module for SendGrid: https://www.drupal.org/project/sendgrid_integration
And Drupal 8 ships with Guzzle in the core of the CMS. 

The Travis builds are failing because I have not fixed the Travis YML. Just no time to do that with all of my other responsibilites at the moment. 

I had the same arguments that you did so I went the route of forking the library and developed my own support for PHP 5.5 and greater. I do not believe in supporting deprecated software, it hurts everyone.

**Comment by achraf52** [comment]
@taz77 Thank you for the great work you've put into this, I hope you find the time to fix the Travis YML so that future users will not be alarmed by the widget and proceed safely to adopt the library.

**Comment by taz77** [comment]
@achraf52 I fixed the build status. It was because I changed version numbers there was a test written to test the version number and it was failing. Now it shows green.

**Pull request closed without merging**
