### PR TITLE
Refactor Code

### PR DESCRIPTION
**Pull request by jopanel**
I believe that most of the functions I removed were redundant. Causing an overly complicated code. Not only for writing this API but for using it. Most people (probably all) will write PHP code connected to some sort of RDBMS. Which means they will pull back objects or an array. In this case I am using array as arrays are preferred in most API I have seen. There are a lot of "new Collection" functions that shouldn't exist. Also there was a lot of random syntax errors and things that don't make sense in regards to posting ("important-key", "important value) but then in the collection it was (["important key" => "important value"]) I think it was just overlooked. However I believe this is the best way to go. This reduces programming time to make the API as well as a friendly environment for integration.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=438) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=438) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=438) it.</sub>

**Comment by shonjord** [comment]
@jopanel First of all, you're not removing `functions` you just removed `objects`, these `objects` are useful, why?, because it allows the library for type hinting and robustness of the code.

This is how the library currently works:

```php
$from = new SendGrid\Email("Example User", "test@example.com");
$subject = "Sending with SendGrid is Fun";
$to = new SendGrid\Email("Example User", "test@example.com");
$content = new SendGrid\Content("text/plain", "and easy to do anywhere, even with PHP");
$mail = new SendGrid\Mail($from, $subject, $to, $content);
```

So, what's the difference with the proposal?, this:

```php
$from = new From("Example User", "test@example.com");
$subject = new Subject("Sending with SendGrid is Fun");
$to = new ToCollection[new To("Example User", "test@example.com")];
$content = new HtmlContent("Whatever");
$mail = new Mail($from, $subject, $to, $content);
```

Do you see any major difference?, because I don't, now the objects represents what they are, and allows the library to validate the data before sending it, how?, well, encapsulating logic inside the objects.

Why do we need collections?, well, same answer, OOP, SRP, DRYP, it allows you and the library for example, filter, map, etc, sometimes these methods are very useful, it doesn't mean you will need them, they're there in case you need them: [PHP Arrays On Steroids](https://scotch.io/tutorials/laravel-collections-php-arrays-on-steroids) , it's not the same collection, but will give you a roughly idea why are these objects useful.

This `Mailer Helper` is basically an object using OOP principles to construct an e-mail and send it, if you don't want to use OOP, just `json_encode `your data and send it, as simple as that, that feature has been available for long time.

**Comment by jopanel** [comment]
Hi,

First off I appreciate your feedback.

I don't believe that you need collections. I assume all major development is done in a OOP style framework of some sort. If its laravel, codeigniter, etc. For a lot of the collections its okay. However it is a bit redundant when it comes to inserting data. It will require additional programming time to create these collection objects that will only make things potentially more complicated. In my opinion.

When it comes to sending out an email you want to call a new object for every single email and put it apart of a collection in an array. It is just very redundant. Why not just have the ability to submit an array or multi-dimensional array without recalling new objects or recalling a collection. I am not saying your way is wrong. I think both of our methods are correct. However I think your method will require additional programming time for something that makes it harder to integrate in a real world scenario. Using OOP or procedural I believe my method is fastest and easiest to work with.

_In this particular case yours is bigger but its not about how big it is, its how you use it._

Also I added the category under customargs. Much needed example that can't be forgotten. 

I work at a business we send 700,000 emails a month through sendgrid. We use V2. It is easy, it is simple, and its no nonsense. This is a lot of nonsense, its complicated, not only for development of the API but for the one integrating it. It is also redundant. Why even add a collection object for something that is an array you won't need to map/sort. Then when you want to insert single items it will need its own custom programming. For every function that can possibly contain a collection you can just loop through an array looking for multiple items to add to the call. Collections are mostly used with Laravel framework. It is just a wrapper around arrays. Why do we need a wrapper for every possible time we insert multi-dimensional arrays? Not everybody is a Laravel fanboy OR wants to use laravel collection functions especially when sending an email. Thats what MySQL is for.

**Comment by shonjord** [comment]
@jopanel First, collections hasn't nothing to do with `Laravel` or any other framework, Java, C# and other languages have these collections natively, and as I said, you don't need to use these methods, they're there if you need them, that's all.

This library is for OOP, as I said before, if you don't want to, you have the freedom to `json_encode`, what stops you for doing it?, I don't see any blocker.

The current version of this mailer class, has the same approach but wrong, the objects don't represent what they are, `To` is not the same as `From`, they're totally different.

And, did I read you well?, instantiating an `object` is time consuming for developers? really?, is that an argument?, it's the same as if I said, I, as a developer, don't want to write a SQL queries, that's time consuming.

If your problem is with the collections, why are you removing every object?, it's not related at all.

This is the way of adding `Tos` using `v2`:

```php
$email->AddTo($useremail)
```
How is this any better than

```php
$email->addTo(new To($userEmail)
```

**Comment by thinkingserious** [comment]
Hello @jopanel,

Thank you for the PR!

@jopanel,

Thank you for taking the time to provide detailed feedback.

I propose that we make collections optional. 

We need to keep the objects in order to provide client side validation and allow for easy subclassing to add custom validation. 

Perhaps we can create another interface for bulk sending that hides the Classes from the user and optimizes for that use case. Or, maybe we just need to provide a better full example that demonstrates grabbing many emails from a DB or similar external source and sending them out in bulk.

Thoughts?

With Best Regards,

Elmer

**Comment by jopanel** [comment]
Like I said,

We are both right. As I stated before. My opinion is for documentation, writeup, and example purposes. Collections should not be used. It should be up to the developer integrating to decide if they want to wrap their arrays in a collection. 

Also saying that writing the additional new To() for every occurrence including additional options isn't time consuming is a joke. Sure its a couple extra characters of unnecessary writing that 99.99% of people using this API won't need. But it will also dramatically cut development time down. At a glance it makes it look overly-complicated just having them there. You have a way you like to do all of your programming. Clearly you like to wrap every array you write in a collection. I will tell you that for sendgrid-api purposes. It is not going to be needed. The ONLY and I mean ONLY reason I can possibly think where it might be used a lot is under "new To". That is ONLY if the collection of emails MUST be sorted because they were gathered in way other than a DB.

**Comment by jopanel** [comment]
Hi Elmer,

Collections should most definitely be optional and not included in the original documentation/examples. In my opinion.

I can understand some of the validation objects and was hesitant to modify them. However I am a V2 user and I do my own validation before sending my emails and if theres anything I miss sendgrid usually picks up "invalid emails" and such. I haven't had a problem.

**Comment by thinkingserious** [comment]
@jopanel,

It sounds like you would like to hide all the objects behind the scenes to make the function signatures easier to use. Correct?

We hope to save you and others the time of having to create those validation objects on your own. 

I like the idea of making the examples very easy to use, especially for the most common cases, but also allowing for added power when needed. I think this can be accomplished with great documentation.

As @shonjord mentioned, simply passing in the JSON is at one end of this spectrum and forcing you to wrap objects around everything at the other. I'm thinking we can meet in the middle and simplify our interfaces while providing examples for the other extremes, for use when needed. 

Some background ... I do love the simplicity of v2 as well, but I also love the new power of v3 (we spent a great deal of time with customers to develop it). Also, it's important to note that all new development will occur on v3. v2 is not deprecated, but will not be updated except for security issues.

With Best Regards,

Elmer

**Comment by jopanel** [comment]
[I created a pull request.](https://github.com/sendgrid/sendgrid-php/pull/439) This is the best we can meet. If somebody wants collections. They are more than welcome to utilize them. Validating objects will still have their purpose. The unnecessary collections are now just arrays. If a programmer wants to utilize a collection they are more than welcome to wrap their arrays on their own merrit.

**Comment by jopanel** [comment]
Also I appreciate all the responses Elmer. I got a chance to participate at a SendGrid conference in Santa Monica earlier this year. I love SendGrid as a ESP. Its a really cool company. I have helped make my company multiple millions utilizing SendGrid ESP and its functions.

**Comment by shonjord** [comment]
I'm against this PR, but that's just me.

I don't see any problem of instantiating objects, that's the nature of OOP, and also don't see the problem of naming objects to represent what they are, it makes the code easy to read.

But anyways, I give up with the OP, he's just against everything and its argument is "I don't want to write code".

Peace out and good luck.

**Comment by jopanel** [comment]
I'm not against everything and my argument isn't that I don't want to write code. Its that I don't want to write useless code. I am sure nobody else want's to write useless code either. You love writing useless code because you can. Thats cool with me but leave the useless code out of the API. If somebody wants to make use of collection class, they can do it.

**Comment by shonjord** [comment]
After watching your repositories and the way you code, I totally understand you know 😃, peace.

**Comment by jopanel** [comment]
There's nothing to see in my repositories. Major projects are in private repos as well other accounts between github and bitbucket. Nice comment though, make sure you wrap it in your useless collections. I would make a collections class function joke like ->forget or ->where, but there is no use for the collection.

**Comment by thinkingserious** [comment]
@shonjord, @jopanel,

Both of you have made great points and illuminated various developer perspectives that are valuable. That is GREATLY appreciated. I believe in the end we will develop a nice, clean and easy to use solution. We are almost there.

One favor please. Let us not continue counter-productive personal attacks and stick to the topics relevant to the SDK. That would also be appreciated :)

With Best Regards,

Elmer

**Comment by jopanel** [comment]
I agree on the personal attacks. I created a new pull request. I think this pull request is invalid after discussing. I am going to close it. My new pull request contains removal of collections. I think there are more valid reasons to not have collections than there are to have them. Its an option as we previously stated but it's unnecessary to have them in both the write-up, or example.

**Pull request closed without merging**
