### PR TITLE
Change documentation according to the PSR-2

### PR DESCRIPTION
**Pull request by lucasmezencio**
According to the PHP-FIG (http://www.php-fig.org/), some PHP implementations need to be standardized.

### CODE REVIEW

**Comment by eddiezane** [comment]
@mbernier can you check this out for me when you get a chance please?

**Comment by mbernier** [comment]
I think it would be a good idea to follow a style guide, if this specific style guide will help interoperability with these other systems, it could be a good idea. 

My only disagreement with them (that I noticed right now) is the requirement to ever put an opening brace on a new line. Other than that, and at first glance, it looks pretty intuitive.

**Comment by lucasmezencio** [comment]
Hi @mbernier! Sorry, dude. My bad.
This pull request is about the docs, but I have pushed some commits that does not belongs to this.

I will cancel this pull request and create another one with the right stuff.

**Comment by mbernier** [comment]
@lucasmezencio I have to admit, I didn't realize this was a PR when I was first brought on, I thought we were discussing the PHP-FIG coding standards. Apologies for my confusion.

We are VERY interested in the changes your made for this PR.  

If possible, we would love it if you could PR this again, in smaller chunks and we will review and then merge. 

Sound good?

**Comment by lucasmezencio** [comment]
Sounds perfectly good, @mbernier!

Thanks!

**Pull request closed without merging**
