### PR TITLE
add checkAgainst method

### PR DESCRIPTION
**Pull request by luqmansungkar**
#483 

Is this enough?

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=508) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=508) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=508) it.</sub>

**Comment by thinkingserious** [comment]
@luqmansungkar

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by luqmansungkar** [comment]
Hi @thinkingserious , thank you for the shirt!

But can you tell me what to change/fix to get this PR merged? I'll try as best as I could.

**Comment by thinkingserious** [comment]
Hi @luqmansungkar,

This PR is on our list to review. I apologize for the delay. We had over 1,000 PRs this month and we are processing them from oldest to newest.

Thank you for your support and patience!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @luqmansungkar,

The only thing missing here is [documentation](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md) and [tests](https://github.com/sendgrid/sendgrid-php/tree/master/test/unit). 

Please add these so that I may complete the code review. Thanks!

With Best Regards,

Elmer

**Comment by childish-sambino** [comment]
Closing due to inactivity. Please ping here if work is to continue.

**Pull request closed without merging**
