### PR TITLE
Issue #458: Make SendGrid permissions management easy

### PR DESCRIPTION
**Pull request by mookman288**
I've hardcoded the values in as expressed in the issue, and the dynamic `__call` special method will determine if the group permissions exist before adding them to the `scopes` collection. 

You can ignore the examples php file if you'd like. 

I won't sign the CLA as it stands because it violates the spirit of the Github CLA and hacktoberfest, but maybe this work can help you moving forward!

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=460) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=460) it.</sub>

**Comment by thinkingserious** [comment]
Thank you @mookman288!

We greatly appreciate your contribution and would love to learn what specifically is bothering you about our CLA. If you prefer to discuss privately, please reach out at dx@sendgrid.com.

With Best Regards,

Elmer

**Comment by mookman288** [comment]
@thinkingserious It is my personal opinion that all of this seems to go against the spirit of open source:

>  - you agree that we may register a copyright in any contribution and exercise all ownership rights associated with it; and
>   - you agree that neither of us has any duty to consult with, obtain the consent of, pay or render an accounting to the other for any use or distribution of any contribution.

>   - make, have made, use, sell, offer to sell, import, transfer and otherwise practice any contribution in whole or in part, alone or in combination with or included in the project or any product, work, or materials arising out of the project; and

And as comparison to the GitHub CLA:

https://cla.github.com/agreement

I believe there's a distinct difference in legalese and intent here. Unfortunately I wasn't aware of these specific lines until after I had completed the work. I hope that sheds light on my view.

**Comment by mbernier** [comment]
@mookman288 [I am not a lawyer and just giving my opinion here] I totally understand the hesitation. We decided a while ago to follow in the footsteps of many companies who are trying to protect the contributors to their open source repositories and themselves when contributing or accepting contributions from the community.

As the person responsible for trying to provide a great experience for developers in our open source and user communities, I hope that the wording we have in our CLA can be seen as a positive and not a negative.

**Comment by thinkingserious** [comment]
@mookman288,

Thank you for taking the time to elaborate.

In thanks for the work you did complete, we would like to offer you some swag. Just simply [fill out this form](https://dx.sendgrid.com/swag). Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
