### PR TITLE
docs: Update documentation for retrieving a list of all templates

### LINKED ISSUE #711: Update documenation for retrieving a list of all templates (dynamic & legacy)
#### Issue Summary

Please update the `USAGE.md` and corresponding `\example` with the call to list all templates. 

This is the API call required: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

#### Acceptance Criteria

* The Usage.md file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic
* The corresponding `/example` file demonstrates how to use this API call to retrieve all templates: GET https://api.sendgrid.com/v3/templates?generations=legacy,dynamic

### PR DESCRIPTION
**Pull request by renshuki**
# Fixes #711 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- I have added in line documentation to the code I modified

### Short description of what this PR does:
 - Update USAGE.md for retrieving a list of all templates (dynamic & legacy)
 - Update /example file for retrieving a list of all templates (dynamic & legacy)

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=717) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=717) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=717) it.</sub>

**Comment by thinkingserious** [comment]
Hello @renshuki,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by CormacBracken** [comment]
This 6-month-old commit contains essential information on using non-legacy templates. It's only documentation, the merge conflict would be trivial to resolve.

**Comment by renshuki** [comment]
I can resolve the conflict if this PR is willing to be merged.

**Pull request merged**
