### PR TITLE
Three brackets in subject

### LINKED ISSUE #723: Document the difference of using three brackets vs two brackets with a template and throw or log an error when used improperly
#### Issue Summary

Our templates use the handlebars.js syntax as documented [here](https://sendgrid.com/docs/ui/sending-email/using-handlebars/). When including the characters ', " or & in a subject line replacement you need to use three brackets vs two ( {{{ content }}} vs {{ content }} ). 

#### Acceptance Criteria

* Documentation of this functionality in the use cases section (transactional templates) of this repo.
* A new test is added that demonstrates that if you use the characters ', " or & in a subject line replacement utilizing template id's prefixed with d-, the code will throw an error or log (to avoid a breaking change) the incident.

### PR DESCRIPTION
**Pull request by gr8shivam**
# Fixes # 
Fixes #723 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds a code to log or throw error if '," or & is found in Subject Line.

### CODE REVIEW

**Comment by gr8shivam** [comment]
@thinkingserious How close I am to solving the issue? Would love to edit as per your suggestions.

**Comment by thinkingserious** [comment]
Hello @gr8shivam,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by childish-sambino** [comment]
@gr8shivam Here's an example of how this was done in Node. Let me know if you have any questions.

https://github.com/sendgrid/sendgrid-nodejs/pull/793

**Comment by childish-sambino** [comment]
Closing due to inactivity.

**Pull request closed without merging**
