### PR TITLE
Phpunit cleanup

### PR DESCRIPTION
**Pull request by brettsantore**
Making it easier to run the tests

### CODE REVIEW

**Comment by mbernier** [comment]
Hey @brettsantore, just wanted to show you our new v3beta branch that we're updating our main branch to soon. We would love your input if you have a minute to check it out! https://github.com/sendgrid/sendgrid-php/tree/v3beta

**Comment by brettsantore** [comment]
I'll take a look! I was going to try and do some maintenance on the master, and didn't notice to v3

**Comment by brettsantore** [comment]
Any chance of moving to PSR-4? I forked the project and started to make some changes/examples to see how difficult it would be. https://github.com/brettsantore/sendgrid-php/tree/psr4

**Comment by thinkingserious** [comment]
Hello @brettsantore,

We are open to using PSR-4. 

In order to accept your pull request, I need to ask for 2 things:
1. Please make your pull request on our beta branch: https://github.com/sendgrid/sendgrid-php/tree/v3beta
2. Please provide us with a signed CLA, per the instructions here: https://github.com/sendgrid/sendgrid-php/blob/v3beta/CONTRIBUTING.md#cla

Thank you!

**Comment by brettsantore** [comment]
Will do

**Pull request closed without merging**
