### PR TITLE
Documentation Path Incorrect: Fixed : spam_reports()

### PR DESCRIPTION
**Pull request by valerianpereira**
Documentation Path Incorrect: Fixed : spam_reports()

File : test/unit/SendGridTest.php

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=451) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=451) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=451) it.</sub>

**Comment by thinkingserious** [comment]
Hi @valerianpereira,

To sign the CLA, you just need to click [this link](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=451) and fill out a short form. I hope that helps!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hi @valerianpereira,

The issue seems to be that you are logged in as @valerianpereira, but the commit is under username @valerian-pereira. I think if you log in as @valerian-pereira, you will be able to sign the CLA.

With Best Regards,

Elmer

**Comment by valerianpereira** [comment]
Thanks. The local github config was messed up globally. Fixed.

Raised a diff PR, deleting the old one.
https://github.com/sendgrid/sendgrid-php/pull/466

Thanks a ton.





Regards,
Valerian Pereira
(9920652827)

**Pull request closed without merging**
