### PR TITLE
wrap name with quotes to manage the v3 API vs v2 differences

### PR DESCRIPTION
**Pull request by cbschuld**
The SG v3 API requires name to be quoted and will not consume double quotes in names.  This PR works around this oddity by sanitizing the name allowing the SDK to blackbox the issue from the caller.

### CODE REVIEW

**Comment by cbschuld** [comment]
@thinkingserious - hold off on this a bit; the test caught an interesting caveat; I'll fix.

**Comment by cbschuld** [comment]
@thinkingserious - Elmer, this one is ready to roll.  Thanks, Chris

**Comment by thinkingserious** [comment]
This looks good to me, thanks!

I just have one more ask, could you please add a few tests that demonstrate a few use cases?

**Comment by thinkingserious** [comment]
Hello @cbschuld,

Just two more things to get this one out the door:

1. Please resolve the branch conflicts
2. Please add a few tests to demonstrate a few use cases

Thanks!

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=370) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=370) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: cbschuld<br/>:x: thinkingserious<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=370) it.</sub>

**Comment by thinkingserious** [comment]
Hi @cbschuld,

I went ahead and resolved the conflicts. I have a couple follow questions/feedback:

1. Why the change to `protected $namespace = \SendGrid::class;`
2. Since this version of the SDK is supporting v3, it should behave how the underlying API is defined as to not cause surprises for those that are starting with v3. I suggest we create a new function to handle this case for legacy users, perhaps with `setv2Name`?

Please let me know what you think. 

Thanks!

Elmer

**Comment by thinkingserious** [comment]
Hi @cbschuld,

Just checking back in with you. Thanks!

**Pull request closed without merging**
