### PR TITLE
feat: Added Data residency for eu and global region

### PR DESCRIPTION
**Pull request by tiwarishubham635**
# Fixes #

Adding data residency with global as the default region and adding support for eu region as well.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/sendgrid/sendgrid-php/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation about the functionality in the appropriate .md file
- [x] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://support.sendgrid.com).

### CODE REVIEW

**Comment by tiwarishubham635** [comment]
The checks are failing as of now since the php-http-client [PR](https://github.com/sendgrid/php-http-client/pull/161) is not merged due to which setHost is not working.

**Review by manisha1997 — APPROVED** [review]

**Comment by tiwarishubham635** [comment]
The php-http-client PR is merged, however it is not released. That's why when `make test-docker` is run, the docker container is not able to pick the merged changes. I am attaching screenshots of the local environment where I manually made changes and the tests are passing. 

Output of `make test`

Screenshot 2023-11-21 at 11 45 43 AM

Output of running the test fie - [DataResidencyTest.php](https://github.com/sendgrid/sendgrid-php/blob/set_data_residency/test/unit/DataResidencyTest.php)

Screenshot 2023-11-21 at 11 46 24 AM

**Review by shrutiburman — APPROVED** [review]

**Review by tbischel — APPROVED** [review]
We probably in all the examples should note that to use the EU region, their subuser must be pinned.  One thing I'm wondering is if we should link to the docs for how subuser pinning will work.  These do not exist yet publicly, so we may want a followup round to add a link to the documentation in example comments next quarter.

**Comment by tbischel** [comment]
There do seem to be a lot of failing checks...

**Comment by shrutiburman** [comment]
> We probably in all the examples should note that to use the EU region, their subuser must be pinned. One thing I'm wondering is if we should link to the docs for how subuser pinning will work. These do not exist yet publicly, so we may want a followup round to add a link to the documentation in example comments next quarter.

Makes sense, I can create a ticket to add the documentation link in all SDKs, when its available publicly.

**Pull request merged**
