### PR TITLE
Use `print_r` instead of `echo` on Arrays.

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Avoids:
```
PHP Notice:  Array to string conversion
```

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=396) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=396) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=396) it.</sub>

**Comment by thinkingserious** [comment]
Hi @ryanpcmcquen,

Thanks for taking the time to make a PR, we really appreciate it!

Only the [$response->headers()](https://github.com/sendgrid/php-http-client/blob/master/lib/Response.php#L27) is an array, could you please adjust accordingly?

Also, for consistency, can you please adjust the other areas in the SDK where we are using `echo` on arrays, such as in README.md.

Thanks!

With Best Regards,

Elmer

**Comment by ryanpcmcquen** [comment]
Thanks! Should be good to go now, here's what I did for reference:

```
for F in `grep -lr 'echo $response' .`; do
  sed -i.backybackybackup 's/echo $response->headers()/print_r($response->headers())/g' $F;
done
for F in `find . -name "*.backybackybackup"`; do
  rm $F;
done
```

**Comment by thinkingserious** [comment]
Hello @ryanpcmcquen,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by ryanpcmcquen** [comment]
Thank you, you're awesome!

**Pull request merged**
