### PR TITLE
chore: Require conformance to style standards

### LINKED ISSUE #702: Require conformance to style standards
#### Issue Summary

In the `CONTRIBUTING.md` file there is a section on Style Guidelines & Naming Conventions. Please review and implement a check in Travis CI. If there are any style errors, either fix or create a rule to exclude the error.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* TravisCI checks that the code conforms to our Style Guidelines & Naming Conventions as defined in our `CONTRIBUTING.md` file
* tests pass locally, in Travis CI and using Docker

### PR DESCRIPTION
**Pull request by jmauerhan**
# Fixes # 
Closes #702 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds codesniffer to the build in CI. 
- The build is currently failing because there are multiple files which do not confirm to the current codesniffer settings. I'd be happy to fix these if requested, or we can do those as a separate PR if it would be cleaner - but as of right now this PR is only the one file, so not a big deal to add the fixes to this.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=725) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=725) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=725) it.</sub>

**Comment by jmauerhan** [comment]
I just reread the issue and saw it does ask that issues be fixed, I'll work on that and re-open :) Sorry about that!

>If there are any style errors, either fix or create a rule to exclude the error.

**Comment by jmauerhan** [comment]
Got all the files updated with formatting fixes, and excluded the SendGrid.php file since it breaks multiple rules, but I'm not going to touch that 😁

**Comment by thinkingserious** [comment]
Hello @jmauerhan,<br /><br/>Thanks again for the PR!<br />                                              <br />It's <a href="https://sendgrid.com/blog/hacktoberfest-2018-has-arrived/">HACKTOBERFEST</a>! We want to show our appreciation by sending                                              you some special Hacktoberfest swag. If you have not already, could you please fill out                                              <a href="https://dx.sendgrid.com/hacktoberfest/join">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Review by childish-sambino — APPROVED** [review]

**Pull request merged**
