### PR TITLE
Fixed minor typo during Mail creation

### PR DESCRIPTION
**Pull request by joeldixon66**
I think you had a very small typo in one of the examples (adding $to instead of the ToCollection $tos).

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=431) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=431) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=431) it.</sub>

**Comment by thinkingserious** [comment]
Thanks @joeldixon66!

Did you have any other feedback on the new prototype? We are looking for at least one more thumbs up so that we may begin development.

With Best Regards,

Elmer

**Comment by joeldixon66** [comment]
No worries @thinkingserious - I'm happy with the new prototype - but I'm new to SendGrid and the php client - so I'm certainly not any authority on the matter. I'm still happy to provide a yes vote if you'd like.

**Comment by thinkingserious** [comment]
Hi @joeldixon66,

Your feedback is still very valuable. It is good to get an objective opinion from someone outside the SendGrid ecosystem, but that has experience with PHP.

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @joeldixon66,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
