### PR TITLE
Added CodeCov support

### LINKED ISSUE #541: Add CodeCov support to .travis.yml
Issue Summary

Add these entries to the .travis.yml file so codecov reports show up!
https://github.com/codecov/example-php/blob/master/.travis.yml

### PR DESCRIPTION
**Pull request by pxgamer**
# Fixes #541 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds support for CodeCov as mentioned in #541 

I haven't checked everything on the list as it wasn't really relevant. I've tested the commit in my Travis CI instance though.
- [Travis Build](https://travis-ci.org/pxgamer/sendgrid-php/builds/294983325)
- [CodeCov](https://codecov.io/github/pxgamer/sendgrid-php/commit/7204c8087e3fc75130e4c29a4ad060b391ccb510)

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=542) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=542) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=542) it.</sub>

**Comment by pxgamer** [comment]
I don't think this can actually be resolved by me, because there was no coverage before as that's the feature I added. 🤔

**Comment by thinkingserious** [comment]
Hello @pxgamer,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@pxgamer 

If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Pull request merged**
