### PR TITLE
Adding Google App engine installation with composer instructions

### LINKED ISSUE #423: Provide Google App Engine GAE instructions
#### Issue Summary

Please see this issue: https://github.com/sendgrid/sendgrid-google-php/issues/6

It should probably go in USE_CASEs and/or TROUBLESHOOTING.

### PR DESCRIPTION
**Pull request by nalinbhardwaj**
Adds `php.ini` file instructions to both files `USE_CASES.md` and `TROUBLESHOOTING.md`

Fixes #423

@thinkingserious please review.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=510) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=510) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=510) it.</sub>

**Comment by thinkingserious** [comment]
@nalinbhardwaj

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by nalinbhardwaj** [comment]
@thinkingserious , thanks a lot, but I already filled this form for a PR on the docs repository, I don’t need to fill it again right?

**Comment by thinkingserious** [comment]
@nalinbhardwaj,

No, you don't need to fill it out again. Sorry for the duplicate request, we are just trying to make sure we don't miss anyone :)

**Comment by thinkingserious** [comment]
Hello @nalinbhardwaj,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
