### PR TITLE
feat: Support for RFC 822 address specification

### LINKED ISSUE #497: Allows users to submit rfc822 formatted email addresses
#### Issue Summary

Similar to: https://github.com/sendgrid/sendgrid-python/pull/348

Where the user can submit email addresses as:
`example@example.com`
or 
`example example <example@example.com>`

### PR DESCRIPTION
**Pull request by kampalex**
Closes #544
Closes #497

# Feature #
Inspired by above mentioned issue/PR to support RFC 822 address specifications.
Implements support of additional formats in `EmailAddress::isEmailAddress()`.

The code will support formats:
```
the@email.address
<the@email.address>
Name<the@email.address>
Name <the@email.address>
```

If providing '>' as last char - and having valid format, the `$emailAddress` argument is updated and validated. The extracted `$name` argument will only be updated if being `null`. Because the arguments are _references_, the updated values are available outside the `isEmailAddress` method.
If `$name` has been given, it will _not_ be updated.

### Checklist
- [X] I acknowledge that all my contributions will be made under the project's license
- [X] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [X] I have read the [Contribution Guidelines](CONTRIBUTING.md) and my PR follows them
- [X] I have titled the PR appropriately
- [X] I have updated my branch with the master branch
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [X] I have added inline documentation to the code I modified

### CODE REVIEW

**Comment by eshanholtz** [comment]
Hey @kampalex 

Thanks for the PR! The SendGrid API actually already accepts RFC 822 email addresses, though it doesn't appear to be documented well. The transformation from `{"email":"Name<the@email.address.com>"}` to `{"email":"the@email.address.com","name":"Name"}` is unnecessary. Only the logic to check that the RFC 822 email is formatted correctly in `isValidEmailAddress` is needed. I can re-review when the changes are made, and test cases are updated.

**Comment by kampalex** [comment]
Hi @eshanholtz
Thanks for your suggestion, but I figured out it doesn't work.
It seems like the API doesn't do any parsing/extraction, it just processed it as-is.

I tested both scenarios by removing the pointers from the arguments of `isValidAddress`. It will pass validation if (real) provided email addresses are valid. (They are.)

**Using in From**
```php
$mail->setFrom(new \SendGrid\Mail\From('Magic test of SendGrid <(localpart)@(domain)>', 'Whoopsie doopsie'));
```
This will create the message header:
```
From: Whoopsie doopsie <Magic test of SendGrid <(localpart)@(domain)>>
```

**Using in To**
```php
$mail->addTo(new \SendGrid\Mail\To('Wild Cat <(localpart)@(domain)>'));
```
This creates a warning in Postfix, because the sender name can't be processed. It ended up as _blocked_. 
```
warning: Illegal address syntax from (...).outbound-mail.sendgrid.net[(...)] in MAIL command: <bounces+16946045-5f3a-wild cat <(localpart)=(domain)>@sendgrid.net>
```
As you see, the whole provided 'address' is merged into the 'bounce address', and therefore cripples the bounce address.

**Comment by eshanholtz** [comment]
@kampalex Can you resolve branch conflicts and I can re-review?

**Comment by kampalex** [comment]
> @kampalex Can you resolve branch conflicts and I can re-review?

I can (but will be late August due to holiday), but are my previous findings fixed in the API?

I figured out (last June, 17th) some scenarios causes failure in delivery, and a decision must be made if the library or API must fix/prevent this. This isn't related to 'PHP only'.

**Comment by childish-sambino** [comment]
Merging of the name and address that's happening on the backend is a bit strange, but the fact that it results in blocked messages when used as the `to` is not good. I've created an internal ticket to track this (ref _EID-3104_).

The immediate fix of allowing such email addresses to pass the client-side address validation would be fine.

**Comment by childish-sambino** [comment]
Closing due to inactivity. Please ping here if work is to continue.

**Pull request closed without merging**
