### PR TITLE
Added ability to provide Email address in new formats

### LINKED ISSUE #497: Allows users to submit rfc822 formatted email addresses
#### Issue Summary

Similar to: https://github.com/sendgrid/sendgrid-python/pull/348

Where the user can submit email addresses as:
`example@example.com`
or 
`example example <example@example.com>`

### PR DESCRIPTION
**Pull request by lribi**
Closes #497 

### Short description of what this PR does:
- Added ability to provide Email address in new formats
- It is now possible to provide Email addresses in the following formats:
example@example.com
example example < example@example.com >

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=544) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=544) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=544) it.</sub>

**Comment by thinkingserious** [comment]
@lrtr

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by lrtr** [comment]
Oh, I completely forgot about my pull request. When I submitted the request, I wasn't able to write the tests because I had problems with my windows laptop. I got a macbook recently and will try again to write the tests. Hope I have time this weekend.

**Comment by thinkingserious** [comment]
Hello @lrtr,

If you are still interested in contributing your changes, please move them to [this function](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/EmailAddress.php#L44).

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks for the updates @lrtr! I've added this to the backlog for a code review.

**Comment by lrtr** [comment]
@thinkingserious Sorry for the delay, there were some projects at work. When I have time I'll look at extending the tests.

**Comment by thinkingserious** [comment]
No worries @lrtr, we appreciate your time!

**Comment by childish-sambino** [comment]
Closing in favor of #979

**Pull request closed without merging**
