### PR TITLE
added support to extend curl options

### PR DESCRIPTION
**Pull request by ninsuo**
This PR add a curlOptions option to merge custom parameters to curl, and add the ability to set a proxy and/or a timeout.

Should be merged after:
https://github.com/sendgrid/php-http-client/pull/11

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome @ninsuo, thanks!

Can you please sign our CLA so we can get this merged? https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md#cla

With Best Regards,

Elmer

**Comment by ninsuo** [comment]
Hi,
How to sign it? I don't see a CONTRIBUTORS file?
Thanks

**Comment by thinkingserious** [comment]
Hi @ninsuo,

You can find the form here: https://drive.google.com/a/sendgrid.com/file/d/0B0PlcM9qA91LN2VEUTJWU2RIVXc/view

Please email the signed version to dx@sendgrid.com

Thanks!

**Comment by ninsuo** [comment]
Ok, I'm abroad right now but will see that next week.

A

**Comment by thinkingserious** [comment]
Thank you @ninsuo!

**Comment by ninsuo** [comment]
Any update on this one?
Thanks

**Comment by thinkingserious** [comment]
Hi @ninsuo,

I am just awaiting the requested changes:

1. Please change the version back to version 5.1.0
2. Please update the dependency to php-http-client to 3.5

Thanks!

**Comment by ninsuo** [comment]
Hi mate,

I done those changes more than 20 days ago in 26880af

Please let me know if you need something else

A

**Comment by ninsuo** [comment]
Hello @thinkingserious 

Requested changes are made since 4 weeks now, it becomes urgent to use this feature in our side.

Can you please have a look?

Thanks,

Alain

**Comment by thinkingserious** [comment]
Hi @ninsuo,

As of right now, this PR is at #7 in our backlog. Apologies for the delay and thanks for the follow up.

**Comment by ninsuo** [comment]
Hello,

Is it possible to get this merged?

Travis fails because this should be merged after sendgrid/php-http-client#11
But everything is perfectly fine and I should release my project tomorrow.

I'll need to use my fork otherwise, not a good practice.

**Comment by thinkingserious** [comment]
Hi @ninsuo,

Unfortunately, this one has not bubbled to the top of our backlog just yet, but it is scheduled for a review and merge.

Looking briefly now, I see there are a couple tests passing. I think you might need to update to v5.1.2.

Thanks for checking in and I'm hoping to get this merged soon.

**Comment by ninsuo** [comment]
Yes you're right, it needed a rebase, that's now ok.

**Comment by thinkingserious** [comment]
Awesome, thanks for the quick update!

**Comment by ninsuo** [comment]
No feedback after almost 3 months, we'll be using our branch as the main one in production.
Thanks anyway

**Comment by thinkingserious** [comment]
@ninsuo,

My apologies :(

I'm glad you got it working in production though.

This is still in our backlog to merge and deploy. Also, for your contribution, we would like to send some swag your way. Could you please fill out this [form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) for us? 

Thanks!

**Comment by ninsuo** [comment]
Please do not merge this one before fixing #17 on php-http-client (i'll need to revert a commit in composer.json).

**Comment by thinkingserious** [comment]
Thanks for the heads up @ninsuo!

**Comment by thinkingserious** [comment]
Note: need to merge this one first https://github.com/sendgrid/php-http-client/pull/16

**Comment by thinkingserious** [comment]
Hi @ninsuo,

We have merged [#17](https://github.com/sendgrid/sendgrid-php/pull/17) on php-http-client and now this one has come up for merge.

Could you please resolve the conflicts?

Thanks!

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Thanks again for the PR @ninsuo! Please take a moment to fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) so we can send you some swag :)

**Pull request merged**
