### PR TITLE
Add PHP 7.1 and 7.2 to Travis build matrix

### PR DESCRIPTION
**Pull request by emirb**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=565) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=565) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=565) it.</sub>

**Comment by thinkingserious** [comment]
Thanks @emirb,

This looks good at first glance. The failing tests are not related to your PR. I have added this to our backlog for final review and merge.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @emirb,

Just wondering why you closed this PR? It's still on our backlog for review and merge.

With Best Regards,

Elmer

**Comment by emirb** [comment]
Reopened now &mdash; I just didn't want it open for 2 months without any activity so I cleaned up my profile a little bit last week.

**Comment by thinkingserious** [comment]
Thanks @emirb!

**Comment by thinkingserious** [comment]
Thanks for taking the time to code review @ssiddhantsharma!

**Comment by emirb** [comment]
Total of 4 months now

**Comment by thinkingserious** [comment]
Thank you for your continued patience @emirb,

We are continuing to work through the over 1,000 Hacktoberfest PRs and we are currenlty down to less than 300 so far. I don't see any issue with merging this one when it comes up next on our backlog.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Hello @emirb,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by emirb** [comment]
Thanks @thinkingserious! :)

**Pull request merged**
