### PR TITLE
PSR1 and PSR2 Conversion

### PR DESCRIPTION
**Pull request by Braunson**
Reference issue #317.

Tried to run tests on current master copy in addition to this PR version, kept getting errors referencing `Class SendGrid` and `Class SendGrid\Client` `not found`. I'm going to assume it's related to this #91

### CODE REVIEW

**Comment by thinkingserious** [comment]
Hello @Braunson,

This is awesome! Thanks for your contribution!

I will look into why the tests are failing.

Could you please take a moment to [sign our CLA](https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md#cla) so I can merge your changes?

Thanks!

**Comment by thinkingserious** [comment]
CLA received, thanks!

**Comment by Dreyer** [comment]
Definitely on board for ditching PEAR for PHP FIG recommendations for coding style conventions.

Although, it looks like this PR, is reverting from the short array syntax back to the long array syntax. From what I can work out, PSR-2 does not seem to make an explicit decision on the short array syntax. However, they do use it in examples in [Chapter 4.3](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods). 

According to the PHP [docs](http://php.net/manual/en/language.types.array.php), unless the intention is for the library to have backward compatibility to support PHP < 5.4, there doesn't seem to be much benefit.

**Comment by thinkingserious** [comment]
@Dreyer,

Thanks for taking the time to provide some feedback!

We do not support versions < 5.4 and do not plan to. That said, the long array syntax does not seem to hurt anything and would probably be helpful to those who must run a version < 5.4.

@Braunson,

Do you have a strong opinion on why we should revert to the long array syntax?

**Comment by Braunson** [comment]
@thinkingserious I'd actually prefer the shorter array syntax but as you said the longer is compatible for people who must run < 5.4.

However according to current [stats](https://laravel-news.com/2016/06/php-version-stats/), the usage as of May 2016, Use of 5.4 and below is ~8% and rapidly dropping. 

I'll adjust the PR to the shorter syntax!

**Comment by SendGridDX** [comment]
Hello @Braunson,

This issue has finally risen to the top of our queue!

I notice that we have a conflicting file, could you please resolve?

Thanks!

Elmer

**Comment by Braunson** [comment]
@SendGridDX I'm not sure if I can edit this PR anymore, the original fork was deleted.

`Braunson  wants to merge 6 commits into sendgrid:master from unknown repository`

**Comment by Braunson** [comment]
@SendGridDX Since I can't edit this PR, I've created a new one from a new fork with the same changes, it should pass tests.  You can find the new PR here #373 . Probably best to close this PR now.

**Pull request closed without merging**
