### PR TITLE
Add license date range unit test

### LINKED ISSUE #532: Add a unittest to check the license.md file date range
The end year in the license file should be "this year" and this should be checked on every run of the tests. If the end year is no correct, fail the test.
example: 
> Copyright (c) 2012-2016 SendGrid, Inc.
It is 2017, so this should be:
> Copyright (c) 2012-2017 SendGrid, Inc.
and the  test should fail.
--done

### PR DESCRIPTION
**Pull request by uppe-r**
Fixes #532 .
Simple unit test to verify if the license file contains the end year as the current one

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=537) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=537) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=537) it.</sub>

**Comment by thinkingserious** [comment]
Hello @uppe-r,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by mbernier** [comment]
@uppe-r 

If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/hacktoberfest-follow-up) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by uppe-r** [comment]
Hey @mbernier , I'd love to! Is there any chance we could talk by text (or you by voice and me by text) instead of video/voice and if so, what is your preferred way?

**Pull request merged**
