### PR TITLE
Style fixes, added phpdoc

### PR DESCRIPTION
**Pull request by ovr**
Hey!

Thanks

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks for the pull request @ovr!

Could you please sign our CLA so we can merge? https://github.com/sendgrid/sendgrid-php/blob/master/CONTRIBUTING.md#cla

**Comment by thinkingserious** [comment]
BTW, the tests are failing because the MOCK_HOST environment variable is not getting set. I'm not sure why and I'm investigating. Seems related to: https://github.com/travis-ci/travis-ci/issues/4885

**Comment by Michal-sk** [comment]
this would help alot!

**Comment by thinkingserious** [comment]
@ovr,

Just a reminder that we will need a signed CLA to merge. Thanks!

**Comment by ovr** [comment]
@thinkingserious Hey! Sorry but I am not intersted to sign CLA for it, closed :(

**Comment by thinkingserious** [comment]
No problem @ovr and thanks for the follow up.

I've created a follow up issue here: https://github.com/sendgrid/sendgrid-php/issues/276

If we had a CLA that could be completed with a form, would that have been acceptable? Or do you have an issue with the legal terms?

Thanks in advance!

**Comment by Caffe1neAdd1ct** [comment]
Just came across this issue due to NetBeans not autocompleting due to properties being incorrectly assigned in a comma separated format.

I may raise a pull request fixing all autocomplete issues after my current project using SendGrid is done.

@thinkingserious may i suggest scrapping the CLA forms in favour of https://cla-assistant.io/ ? FOSS developers are more likely to contribute with this in place (have a look at owncloud for how the cla signing process hooks in with pull requests).

**Comment by thinkingserious** [comment]
Hello @Caffe1neAdd1ct,

Thanks for the suggestion! I've passed cla-assistant.io along to our legal team for review. I hope we can implement it :)

**Pull request closed without merging**
