### PR TITLE
Attachments now automatically get base64 encoded if they are not already

### LINKED ISSUE #611: Detect if an attachment is Base64 encoded, if not, automatically encode it
#### Issue Summary

This should be done in the `[setContent](https://github.com/sendgrid/sendgrid-php/blob/master/lib/mail/Attachment.php#L78)` method of the Attachment object.

[See here for an example](https://github.com/sendgrid/sendgrid-php/blob/master/USE_CASES.md#attachments).

### PR DESCRIPTION
**Pull request by martijnmelchers**
# Fixes # 
Fixes #611 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- When an attachement is added it first checks whether or not it has already been base64 encoded, if not it encodes its.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=618) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/sendgrid-php?pullRequest=618) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/sendgrid-php?pullRequest=618) it.</sub>

**Comment by thinkingserious** [comment]
Nicely done @martijnmelchers!

We just need to add some tests to get this one merged. Do you have time to do that?

**Comment by martijnmelchers** [comment]
Sure will do that today!

**Comment by martijnmelchers** [comment]
@thinkingserious In what file should the tests be created?

**Comment by thinkingserious** [comment]
How about `Attachments.php` in `[/test/unit/]`(https://github.com/sendgrid/sendgrid-php/tree/master/test/unit)

BTW, have you been able to get the tests running locally using [Docker](https://github.com/sendgrid/sendgrid-php/tree/master/docker)?

**Comment by martijnmelchers** [comment]
I'm not able to get the Docker thing running, so I might not be able to run tests. How should I proceed?

**Comment by thinkingserious** [comment]
I will help you with that. Please email me at dx@sendgrid.com and let me know where you are stuck. Thanks!

**Comment by martijnmelchers** [comment]
There seems to be a difference in PHP 7.1 and up with `base64_decode` any solutions you can think of @thinkingserious

**Comment by thinkingserious** [comment]
Awesome! Is this ready to go?

**Comment by martijnmelchers** [comment]
Yes it can be merged!

Op wo 23 mei 2018 18:17 schreef Elmer Thomas <notifications@github.com>:

**Comment by thinkingserious** [comment]
Hello @martijnmelchers,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
